# Generated by Django 4.0.6 on 2024-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('bedrooms', models.TextField(blank=True, null=True)),
                ('bathrooms', models.TextField(blank=True, null=True)),
                ('sqft_living', models.TextField(blank=True, null=True)),
                ('sqft_lot', models.TextField(blank=True, null=True)),
                ('floors', models.TextField(blank=True, null=True)),
                ('waterfront', models.TextField(blank=True, null=True)),
                ('view', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('grade', models.TextField(blank=True, null=True)),
                ('sqft_above', models.TextField(blank=True, null=True)),
                ('sqft_basement', models.TextField(blank=True, null=True)),
                ('yr_built', models.TextField(blank=True, null=True)),
                ('yr_renovated', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, null=True)),
                ('sqft_living15', models.TextField(blank=True, null=True)),
                ('sqft_lot15', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'houses',
                'managed': False,
            },
        ),
    ]
